config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  get '/contact', to: "contact#show"  
  get '/team', to: "team#index"
  resources :registration
  get '/home', to: 'home#index'
  get '/home/login',to: 'home#login'
  post '/home/login',to: 'home#check'
  post '/home', to: 'home#deconnect'
  resources :gossip
  resources :home
  post '/gossip/comment', to: "comment#create"
  patch '/comment/:id/update', to: "comment#update"
  post '/gossip/like', to: "like#create"
  resources :like
  resources :comment  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
  has_many :likes, as: :likable
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user, optional: true
  has_many :comments, as: :commentable
  has_many :likes, as: :likable
  has_and_belongs_to_many :tags
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likable, polymorphic: true
end

app/models/pm.rb
class Pm < ApplicationRecord
  belongs_to :sender, class_name: "User", foreign_key: "sender_id"
  has_and_belongs_to_many :users
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :gossips
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :pms, through: :recipients
  belongs_to :city 

  #validates :first_name, presence: { message: 'ne doit pas être vide'}
  #validates :last_name, presence: { message: 'ne doit pas être vide'}
  #validates :email, presence: { message: 'ne doit pas être vide'}
  #validates :password, presence: { message: 'ne doit pas être vide'}
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  def new
    @good_comment = Comment.new
    @comment_original= Comment.find(params[:comment_id])
  end

  def create 
    if session[:user_id]
      user = User.find(session[:user_id])
    else
      user = User.create!(city:City.first, first_name: "Ano", last_name: "Nimus", email: "ano.nimus@anomymus.com")
    end  
    if params[:gossip_id]
      gossip = Gossip.find(params[:gossip_id])
      new_comment = gossip.comments.create!(content: params[:comment][:content], user: user)
    else
      puts 'moi'
      puts params[:comment][:comment_id]
      puts params[:comment_id]
      comment= Comment.find(params[:comment_id])
      new_comment= comment.comments.create!(content: params[:comment][:content], user: user)
      gossip = comment.commentable
    end
    url="/gossip/" + gossip.id.to_s
    redirect_to(url)
  end

  def edit
    @good_comment = Comment.find(params[:id]) 
  end

  def update
    @good_comment = Comment.find(params[:id]) 
    @good_comment.update_attributes(content: params[:comment][:content])
    url="/gossip/" + @good_comment.commentable.id.to_s
    redirect_to(url)
  end
    
  def destroy
    @good_comment = Comment.find(params[:id])
    url= @good_comment.commentable.id.to_s
    if session[:user_id]
      user = User.find(session[:user_id])
      if user == @good_comment.user
        @good_comment.destroy
      end
    end
    redirect_to("/gossip/"+url)
  end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def show
    
  end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  
  def index
    @gossip =Gossip.order(:id) 

  end
  
  def show
    @comment = Comment.order(:id)
    @good_coms = []
    @good_gossip = Gossip.find(params[:id])
    @comment.each do |comment|
      if comment.commentable == @good_gossip
        @good_coms << comment
      end
    end
    @good_comment = Comment.new
    @number_likes = []
    @good_gossip = Gossip.find(params[:id])
    @like = Like.order(:id)
    @like.each do |like|
      if like.likable == @good_gossip
        @number_likes << like
      end
    end
    @good_like = Like.new
  end

  def new
    @gossip = Gossip.new
  end

  def create 
    if session[:user_id] 
      @u = User.find(session[:user_id])
    else 
      @u=User.create!(city:City.first, first_name: "Ano", last_name: "Nimus", email: "ano.nimus@anomymus.com")
    end
    @gossip = Gossip.create!(user: @u, title: params[:gossip][:title], content: params[:gossip][:content], date: Time.now)
    url="/gossip/" + @gossip.id.to_s
    redirect_to(url)
  end

  def edit
    @gossip = Gossip.find(params[:id])
    @user = User.new
    @city_user = City.new
  end
  
  def update
    @gossip = Gossip.find(params[:id])
    # @city_all.each do |city|
    #   if city_exist(city, params[:postal])
    #     @city_user = city_exist(city, params[:postal])
    #   end
    # end
    # @user_all.each do |user|
    #   if user_exist(user, params[:first_name], params[:last_name], params[:email])
    #     @user_here = user_exist(user, params[:first_name], params[:last_name], params[:email])
    #   end
    # end
    # # différends cas suivant si l'user existe déjà, ou si la ville existe déjà
    # if @user_here
    #   if @city_user
    #     if @user_here.city_id == @city_user.id
    #       @gossip = @gossip.uptade_attributes(user: @user_here, title: params[:gossip][:title], content: params[:gossip][:content], date: Time.now)
    #     else
    #       @user_here = @user_here.update_attributes(city: @city_user)
    #       @gossip = @gossip.uptade_attributes(user: @user_here, title: params[:gossip][:title], content: params[:gossip][:content], date: Time.now)
    #     end
    #   end
    # elsif @city_user
    #   @user_here = User.create!(first_name: params[:first_name], last_name: params[:last_name], email: params[:email], city: @city_user)
    #   @gossip = @gossip.update_attributes(user: @user_here, title: params[:gossip][:title], content: params[:gossip][:content], date: Time.now)
    # else
    @city_user = City.create!( name: params[:city], postal_code: params[:postal]) 
    @user = User.create!(first_name: params[:first_name], last_name: params[:last_name], email: params[:email], city: @city_user)
    @gossip.update_attributes!(user: @user, title: params[:title], content: params[:content], date: Time.now)
    
    url="/gossip/" + (@gossip.id-1).to_s
    redirect_to(url)
  end

  # def city_exist(city,postal)
  #   if city.postal_code == postal
  #     return city
  #   end
  # end

  # def user_exist (user, first_name, last_name,email)
  #   if user.first_name == first_name && user.last_name == last_name && user.email == email
  #     return user
  #   end
  # end


  def destroy 
    if session[:user_id]
      @gossip = Gossip.find(params[:id])
      user = User.find(session[:user_id])
      if user == @gossip.user
        
        @gossip.destroy
      end
    end
    redirect_to("/gossip")
  end
  
  


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
    
  def login
    @current_user = User.new
  end
    
  def check
    @current_user = User.where(email: params[:user][:email], password: params[:user][:password]).first
    if @current_user
      session[:user_id] = @current_user.id
      puts session[:user_id]
      flash[:info] = "Vous êtes maintenant connecté"
      redirect_to "/home"
    else
      session[:user_id] = nil
      flash[:info] = "Échec de la connexion"
      puts "Echec"
      redirect_to "/home/login"
    end
  end

  def deconnect
    session[:user_id] = nil
    flash[:info] = "User déconnecté"
    redirect_to "/home"
  end

end

app/controllers/like_controller.rb
class LikeController < ApplicationController
    def new
        @good_like = Like.new
    end

    def create 
        puts params
        gossip = Gossip.find(params[:gossip_id])
        puts session[:user_id]
        if session[:user_id]
            like = gossip.likes.create!(user: User.find(session[:user_id]))
        end
        url="/gossip/" + gossip.id.to_s
        redirect_to(url)
    end
    
    def destroy
        @good_like = Like.find(params[:id])
        url= @good_like.likable.id.to_s
        @good_like.destroy
        redirect_to("/gossip/"+url)
    end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/contact/show.html.erb
<%= render "shared/header" %>

<body class="bg-secondary text-light d-flex align-items-stretch flex-wrap">
  <div class="bg-secondary text-light d-flex align-items-stretch flex-wrap container-fluid">
    <h4><br/>Bientôt un formulaire de contact :)</h4>
  </div>
</body>

app/views/gossip/edit.html.erb
<%= render "shared/header" %>

<body class="bg-secondary text-light d-flex align-items-stretch flex-wrap">
	<div class="container-fluid">
		<h3><br/>Veuillez remplir le formulaire suivant pour éditer votre potin</h3>
		<form  class= "col-md-6" action="/gossip/<%= @gossip.id %>" method="POST">
			<input name="_method" type="hidden" value="patch" />
			<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
			<div class="form-row">
				<div class="form-group col-md-6">
					<label for="first_name">Nouveau prénom de l'auteur</label>
					<input class="form-control" type="text" name="first_name" placeholder="jean">
				</div>
				<div class="form-group col-md-6">
					<label for="last_name">Nouveau nom de l'auteur</label>
					<input class="form-control" type="text" name="last_name" placeholder="dupont">
				</div>
				<div class="form-group col-md-6">
					<label for="email">Nouvel email de l'auteur</label>
					<input class="form-control" type="text" name="email" placeholder="jean.dupont@mail.com">
				</div>
				<div class="form-group col-md-6">
					<label for="city">Nouvelle ville de l'auteur	</label>
					<input class="form-control" type="text" name="city" placeholder="Marseille">
				</div>
				<div class="form-group col-md-12">
					<label for="postal">Code postal de la ville</label>
					<input class="form-control" type="text" name="postal" placeholder="13000">
				</div>
			</div>

			<div class="form-row ">
				<div class="form-group col-md-12">
					<label for="title">Nouveau titre du potin</label>
					<input class="form-control" type="text" name="title" placeholder="On ne fornique plus">
				</div>
			</div>
			
			<div class="form-row flex-column">	
				<div class="form-group col-md-12">
					<label for="content">Nouveau contenu du potin</label>
					<textarea class="form-control" rows="3" name="content" placeholder="Vous savoir quoi de plus? Voyeurs !"></textarea>
				</div>

				<div class="form-group col-md-12  align-items-stretch ">
					<button type="submit" class="btn-block 	btn btn-outline-success bg-light" >Valider</button>
				</div>
			</div>
		</form>
	</div> 	
</body>

app/views/gossip/index.html.erb
<%= render "shared/header" %>

<body class="bg-secondary text-light d-flex align-items-stretch flex-wrap">
  <section class="container-fluid">
    <div class= "text-light  d-flex align-content-end flex-wrap ">
      <p class="p-6"><br/>Salut ! Ici c'est notre super index des potins, il est chouette, non ?<br/></p>
    </div>
    <div class="container-fluid d-flex align-content-between justify-content-between flex-wrap">
      <% @gossip.each do |gossip| %>
        <div class = "card" style = "width: 25rem;">
          <div class="bg-light text-dark">
            <div class = "card-body">
              <h6 class = "text-success">Gossip n°: <%= gossip.id%></h6>
              <p class = "card-text">
                Ecrit par: <%= gossip.user.first_name %> <%= gossip.user.last_name %><br/>
                Titre : <%= gossip.title%><br/>
                Contenu : <%= gossip.content %><br/>
                <small>
                  Nombre de commentaire : <%=gossip.comments.count%><br/>
                  Nombre de like : <%=gossip.likes.count%><br/>
                </small>
              </p>
              <p class= "flex-wrap">
                <a href="/gossip/<%= gossip.id %>" class="card-link">Lien vers le potin ici</a> 
                <a href="/gossip/<%= gossip.id%>/edit" class="card-link">Editer le potin ici</a>

              </p>
            </div>
          </div>
        </div>
        <br/>
      <% end %> 
    </div>
  </section>
</body>

app/views/gossip/new.html.erb
<%= render "shared/header" %>

<body class="bg-secondary text-light align-items-stretch ">
	<div class="container-fluid">
		<h3><br/>Pour inscrire votre potin, veuillez le rentrer ci-dessous</h3>
		<div class="form-row">

		<%= form_for @gossip, url: {action: "create"}, html: {class: "col-md-6"} do |f| %>
			
			<div class="col-md-6">
				<div class="form-group">
					<%= f.label "Le titre de votre gossip"%>
					<%= f.text_field :title, placeholder: 'Ici, on fornique', class: "form-control" %>
				</div>			
			</div> 
			

			<div class="col-md-12 form-group">
				<%= f.label "Le contenu de votre gossip"%>
				<%= f.text_area :content, size: "30x3", placeholder: 'Haha, vous voudriez bien savoir hein?', class: "form-control" %>
			</div>

			<div class="col-md-12 form-group  text-light">
				<%= f.submit "Valider", class: "btn btn-outline-success bg-info col-md-12 align-items-stretch	text-light" %>
			</div>
		<% end %>
		</div>
	</div>
</body>

app/views/gossip/show.html.erb
<html>
<%= render "shared/header" %>

  <body class="bg-secondary text-light">
  <div class="container">
  <div class="row">
  

    <div class="col-md-6"><br/><br/>
      <!-- Affichage du potin -->
      
      <h2>Titre : <%= @good_gossip.title %></h2>
      <small>Potin n°<%= @good_gossip.id%></small>
      <small>Son auteur est <%= @good_gossip.user.first_name %> <%= @good_gossip.user.last_name %></small>
      <small>Date de création :  <%= @good_gossip.date %></small><br/><br/>
      <h5>#Balancetongossip : "<%= @good_gossip.content %>"</h5>
      
      <!-- Like -->
      <p class = flex-row>
        <%= @good_gossip.likes.count %> personne(s) ont déjà liké
        <br/>
      </p>
      <div class="container-fluid">
        <div class= "justify-content-end" >
        <p> 
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          
          <% if @current_user == nil%>
            <%= link_to "Enregistre-toi pour pouvoir liker!", '/registration/new', class: "btn btn-lg btn-primary" %>
          <% elsif @good_gossip.likes.where( :user_id == session[:id]).first%>
            <%= link_to 'Enlever le like', "/like/"+@good_gossip.likes.where( :user_id == session[:id]).first.id.to_s , data: {:confirm => 'Êtes-vous sûr?'}, class: "btn btn-outline-success bg-info text-light", :method => :delete %>
          <% else%>
            <%= form_for @good_like, :url => '/gossip/like', html: {class: "col-md-6"} do |f| %>
              <%=hidden_field_tag "gossip_id", @good_gossip.id%>
            <%= f.submit "Like", class: "btn btn-outline-success bg-info text-light" %>
            <% end %>
        
          <% end %> 
        </p>
        </div>

        <!-- Boutons Retour à l'accueil, Editer le gossip, Détruire le gossip -->
        <div class= "justify-content-between" >
          <%= link_to "Retouner à l'index", '/gossip', class: "btn btn-success" %>
          <%= link_to "Editer le gossip", '/gossip/'+@good_gossip.id.to_s+'/edit', class: "btn btn-success" %>
          <%= link_to 'Détruire le gossip', @good_gossip, class: "btn btn-success", data: {:confirm => 'Êtes-vous sûr?'}, :method => :delete %>
        </div>
        <br/>
      </div>
     
      <!-- Création de potin -->
      <div>
        <h6>Inscrivez votre commentaire ci-dessous</h6>
		    <%= form_for @good_comment, :url => "/comment", html: {class: "col-md-6"} do |f| %>
			    <%=hidden_field_tag "gossip_id", @good_gossip.id%>			
			    <div class=" form-row">
				    <%= f.text_area :content, size: "30x3", placeholder: 'Haha, super ce potin', class: "form-control" %>
          </div>
			    <div class=" form-group  text-light">
				    <%= f.submit "Valider", class: "btn btn-outline-success bg-info btn-block align-items-stretch	text-light" %>
			    </div>
		    <% end %>
      </div>
    
    </div><br/>
      
    

   <!-- Affichage du comment -->
    <div class="col-md-6"><br/><br/>
      <% @good_coms.each do |comment| %>
        <div class = "card" style = "width: 100%;">
        <div class="bg-light text-dark">
        <div class = "card-body">
        <h6 class = "card-text">
          <small>Commentaire<br/>L'auteur: <%= comment.user.first_name %> <%= comment.user.last_name %></small><br/>
          <%= comment.content %>
        </h6>
        <div class="container">
        <p class= "justify-content-between">
          <small><a href="/comment/<%= comment.id%>/edit" class="card-link">Editer le commentaire ici</a> &nbsp;&nbsp;&nbsp;&nbsp;   
          <%= link_to "Commenter", new_comment_path(:comment_id => comment.id) %> </small>        
        </p>
        </div>
        <% comment.comments.each do |comment| %>
          <div class = "justify-content-end">
          <p class = "card-text ">
            <small>Sous-commentaire<br/>L'auteur: <%= comment.user.first_name %> <%= comment.user.last_name %></small><br/>
            <%= comment.content %>
          </p>
          </div>
        <% end %> 
        </div>
        </div>
        </div><br/><br/>
      <% end %> 
    
    </div>
    </div>
  </div>
  </div>
  </body>
</html>

app/views/home/index.html.erb
<%= render "shared/header" %>

<body class="bg-secondary text-light d-flex align-items-stretch flex-wrap">

<div class="container-fluid align-items-stretch bg-secondary">
<div class= "text-light  d-flex align-content-end flex-wrap ">
<div class="center jumbotron bg-secondary">       
  <% if @current_user %>
    <h1>Bienvenue <%= @current_user.first_name %> !</h1>
    <%= link_to "Déconnexion", '/home', method: :post, class: "btn btn-lg btn-primary" %>

  <% else %>    
    <h1>Bienvenue visiteur anonyme!</h1>
      <h3>
        Ici, tu peux retrouver les moussaillons 🎓
      </h3>
    <%= link_to "Enregistre-toi !", '/registration/new', class: "btn btn-lg btn-primary" %>
    <%= link_to "Connecte-toi !", '/home/login', class: "btn btn-lg btn-primary" %>
  <% end %>  
</div>
</div>
</div>

</body>

app/views/home/login.html.erb
<%= render "shared/header" %>

<body class="bg-secondary text-light align-items-stretch ">
	<div class="container-fluid">
		<h3><br/>Login</h3>
		<div class="form-row">

		<%= form_for @current_user, url: "/home/login", html: {class: "col-md-6"} do |f| %>
			
			<div class="col-md-6">
				<div class="form-group">
					<%= f.label "Entrez votre email" %>
					<%= f.text_field :email, placeholder: 'Email', class: "form-control" %>
				</div>			
			</div> 

            <div class="col-md-6">
				<div class="form-group">
					<%= f.label "Entrez votre mot de passe" %>
					<%= f.password_field :password, placeholder: 'Mot de passe', class: "form-control" %>
				</div>			
			</div> 

			<div class="col-md-12 form-group  text-light">
				<%= f.submit "Valider", class: "btn btn-outline-success bg-info col-md-12 align-items-stretch	text-light" %>
			</div>
		<% end %>
		</div>
	</div>
</body>

app/views/team/index.html.erb
<%= render "shared/header" %>

<body class="bg-secondary text-light d-flex align-items-stretch flex-wrap">
  <div class="container-fluid">
    <br/>
    <h5>Voici notre superbe équipe 😇❤️😻</h5>
    <ul>
      <li> Fayçal, slack @Fays</li>
      <li> Hai-Dang, slack @Hai-dang</li>
      <li> Guillaume, slack @Guillaume </li>
    </ul>
  </div>
</body>